name: flutter_login_ui
description: A new Flutter template for Logging in.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/  #declares all the content of the directory as assets

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf

